using System.Collections.Generic;
using Newtonsoft.Json;

namespace JourneyPlanner.Models.RTT
{
    //File Generated by quicktype.io
    public partial class RttServiceList
    {
        [JsonProperty("location")]
        public Ation Location { get; set; }

        [JsonProperty("filter")]
        public Filter Filter { get; set; }

        [JsonProperty("services")]
        public List<RttService> Services { get; set; }
    }

    public partial class Filter
    {
        [JsonProperty("destination")]
        public Ation Destination { get; set; }
    }

    public partial class Ation
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("crs")]
        public string Crs { get; set; }

        [JsonProperty("tiploc")]
        public string Tiploc { get; set; }
    }

}
