services:
  web:
    build: './JourneyPlanner/'
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
  mysql:
    image: mysql:5.6.40
    networks:
      - backend
    volumes:
      - ./Database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'JourneyPlanner'
networks:
  frontend:
  backend: